create table film
(
    id          int auto_increment
        primary key,
    description varchar(255) null,
    genre       int          null,
    image       varchar(255) null,
    rating      float        null,
    title       varchar(255) not null,
    year        int          null
);

INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (1, 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.', 1, 'https://tinyurl.com/bzwr6bb9', 10, 'Spider-Man: Across the Spider-Verse', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (2, 'A young mermaid makes a deal with a sea witch to trade her beautiful voice for human legs so she can discover the world above water and impress a prince.', 1, 'https://tinyurl.com/munmurrb', 0, 'The Little Mermaid', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (3, 'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.', 0, 'https://tinyurl.com/msckmavt', 4.5, 'John Wick: Chapter 4', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (4, 'Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.', 1, 'https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 8.5, 'Guardians of the Galaxy Vol. 3', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (5, 'Follows the history of sports marketing executive Sonny Vaccaro, and how he led Nike in its pursuit of the greatest athlete in the history of basketball, Michael Jordan.', 3, 'https://m.media-amazon.com/images/M/MV5BYmNlOTNlYjUtM2U3Yy00M2ZjLTkxZDQtN2NiNGZiZDI0ZjE3XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 9, 'Air', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (6, 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 1, 'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg', 10, 'Spider-Man: Into the Spider-Verse', 2018);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (7, 'A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.', 2, 'https://m.media-amazon.com/images/M/MV5BOTJhNzlmNzctNTU5Yy00N2YwLThhMjQtZDM0YjEzN2Y0ZjNhXkEyXkFqcGdeQXVyMTEwMTQ4MzU5._V1_.jpg', 8.5, 'The Super Mario Bros. Movie', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (8, 'A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.', 2, 'https://m.media-amazon.com/images/M/MV5BNmFkN2M2NzItOTY5YS00MmE2LTk3ZjctNTk2YzQ5ZmRiYzJjXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg', 8, 'Dungeons & Dragons: Honor Among Thieves', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (9, 'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.', 0, 'https://m.media-amazon.com/images/M/MV5BOWZhYjY4ZjgtOWJhNS00Y2E2LTkzYWMtNzY3ZTFiNDUyZTBlXkEyXkFqcGdeQXVyMTMzNzIyNDc1._V1_.jpg', 7, 'The Covenant', 2023);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (10, 'Shubh returns for revenge and this season he takes the challenge to a whole new level. With the heroes fallen apart, will a desolate Dhananjay Rajpoot and a torn Nikhil Nair be able to stop him?', 3, 'https://m.media-amazon.com/images/M/MV5BNjczODVjMmMtNTVlNy00MjlkLWEyZjYtOThiYzMwZmIyNWZkXkEyXkFqcGdeQXVyMTY0NjI3Mjcx._V1_.jpg', 9, 'Asur: Welcome to Your Dark Side', 2020);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (11, 'American college football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League football team.', 3, 'https://m.media-amazon.com/images/M/MV5BMTdmZjBjZjQtY2JiNS00Y2ZlLTg2NzgtMjUzMGY2OTVmOWJiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg', 0, 'Ted Lasso', 2021);
INSERT INTO film_rating.film (id, description, genre, image, rating, title, year) VALUES (12, 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Navi race to protect their home.', 0, 'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_.jpg', 3, 'Avatar: The Way of Water', 2022);